name: pip-audit
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3
       - name: install
         run: python -m pip install safety
         run: safety check -r requirements.txt

      
