name: pip-audit
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3
       - name: install
         run: python -m pip install .
       - uses: pypa/gh-action-pip-audit@v1.0.8
         with:
          local: true
          inputs: requirements.txt
